# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    environment:
      IMAGE_NAME: arundocker017/datasette-new
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Build Docker Image
         command: docker build -t $IMAGE_NAME:latest .
workflows:
  # Name the workflow "welcome"
  build-branch:
    # Run the welcome/run job in its own container
    jobs:
      - build
